#Application name
spring.application.name=InventoryService

# Server Configuration
server.port=8084

#spring.application.name=INVENTORY-SERVICE

# Database Configuration (H2 for development, use PostgreSQL/MySQL in production)
spring.datasource.url=jdbc:h2:mem:inventorydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
#Enable H2 Database Console (for testing)

# JPA & Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Show SQL queries in logs

spring.security.basic.enabled=false

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# Actuator Endpoints (For Monitoring & Health Checks)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always



#spring.security.user.name= admin
#spring.security.user.password= admin


# Define the location for log files
logging.file.name=C://Users/somyagupta01/myProjects/microservices/logs/zion.log